/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 29 Nov, 2012, 11:12:36 PM
 */
package javaapplication2;
import java.sql.*;

/**
 *
 * @author savita
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        try {
            Class.forName("org.postgresql.Driver");
            Connection cn = DriverManager.getConnection("jdbc:postgresql://localhost/postgres","postgres","dbms");
            Statement stmt = cn.createStatement();

        // TODO add your handling code here:
        //Connect DB, UN ....
            //System.out.print(txtUN.getText() + "\n");
            String entered_password = jPasswordField1.getText();
            //System.out.print(entered_password + "\n");
            String entered_username = txtUN.getText();
            
            /*String s = "Insert into login_student values('abc','123')";
            ResultSet res = stmt.executeQuery(s);*/
            
            String st = "Select password from login_student" + " where username = '" + entered_username + "'";
            /*PreparedStatement ps = cn.prepareStatement(st);
            ps.setString(1, entered_username);
            ps.executeUpdate();*/
            //System.out.println("Printing the query : " + st);
            ResultSet res = stmt.executeQuery(st);
            res.next();
            String check = res.getString("password");
            System.out.println("password : " + check);
            System.out.println("entered password : " + entered_password);
            //String ch = "amma"
            if (entered_password.equals(check)) { //After success       
                System.out.println("OK");
                option op = new option();
                op.setVisible(true);
                this.dispose();
            }
        }
        catch(Exception e) {
            System.out.println("Exception caught" + " " + e + "  ");
        }
        
        
    }//GEN-LAST:event_butLoginActionPerformed
    
    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    private void butLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butLoginMouseEntered
        // TODO add your handling code here:
        System.out.print("##############");
    }//GEN-LAST:event_butLoginMouseEntered

    private void txtUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNActionPerformed

    
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtUN;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
